#!/usr/bin/env node
const { execSync } = require('child_process')
const { readdir, writeFile } = require('fs').promises

try {
  execSync('chmod +x ./bin/*')
} catch (err) {
  console.log('chmod err', err)
}

const updatePackageBins = async () => {
  const bins = await readdir('./bin')
  const package = require('../package.json')
  package.bin = {}
  bins.forEach(binName => {
    package.bin[binName] = `bin/${binName}`
  })
  updatedPackage = JSON.stringify(package, null, 2) + '\n'
  await writeFile('./package.json', updatedPackage)
  console.log('updated packages')
}

updatePackageBins()
.catch(console.error)
